services:
  data:
    build:
      context: ./data
    container_name: data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - internal
      - public

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ssafy
      POSTGRES_PASSWORD: ssafy1234
      POSTGRES_DB: app
    volumes:
      - /srv/souffle/volumes/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssafy"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - internal

networks:
  public:
  internal:

