services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL}
    ports:
      - "3000:3000"
    networks:
      - public

networks:
  public:
  internal:
